const sections = document.querySelectorAll('.page-section');
const navItems = document.querySelectorAll('.nav-item');
const titleMap = {dashboard:'Engagement Dashboard',live:'Live Engagement Analysis',video:'Video Analysis',reports:'Analysis Reports'};
function showSection(id){
  sections.forEach(s=>s.classList.toggle('active-section',s.id===id));
  navItems.forEach(n=>n.classList.toggle('active',n.dataset.section===id));
  document.getElementById('pageTitle').textContent=titleMap[id];
  window.scrollTo({top:0,behavior:'smooth'});
}
navItems.forEach(n=>n.addEventListener('click',()=>showSection(n.dataset.section)));
document.querySelectorAll('[data-goto]').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.goto)));

const canvas=document.getElementById('trendChart');
const ctx=canvas.getContext('2d');
function drawChart(){
  const dpr=window.devicePixelRatio||1, rect=canvas.getBoundingClientRect();
  canvas.width=rect.width*dpr; canvas.height=rect.height*dpr; ctx.scale(dpr,dpr);
  const w=rect.width,h=rect.height,p=20;
  const data=[61,65,63,70,68,74,72,79,76,82,80,86,82,88,84,82];
  ctx.clearRect(0,0,w,h);
  ctx.strokeStyle='#e9edf3';ctx.lineWidth=1;
  for(let i=0;i<4;i++){const y=p+i*(h-2*p)/3;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke();}
  ctx.beginPath();
  data.forEach((v,i)=>{const x=p+i*(w-2*p)/(data.length-1),y=h-p-(v-50)*(h-2*p)/50;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});
  ctx.strokeStyle='#6278f5';ctx.lineWidth=3;ctx.stroke();
  ctx.lineTo(w-p,h-p);ctx.lineTo(p,h-p);ctx.closePath();
  const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'rgba(98,120,245,.20)');g.addColorStop(1,'rgba(98,120,245,0)');
  ctx.fillStyle=g;ctx.fill();
}
window.addEventListener('resize',drawChart); drawChart();

const fileInput=document.getElementById('videoInput');
fileInput?.addEventListener('change',e=>{
  document.getElementById('fileName').textContent=e.target.files[0]?.name||'No video selected';
});

let stream=null;
const video=document.getElementById('camera');
document.getElementById('startCamera')?.addEventListener('click',async()=>{
  try{
    stream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});
    video.srcObject=stream;video.hidden=false;document.getElementById('cameraPlaceholder').hidden=true;
    document.getElementById('cameraStatus').textContent='Camera active';
  }catch(err){alert('Camera access was not granted. Allow camera permission in your browser and try again.');}
});
document.getElementById('stopCamera')?.addEventListener('click',()=>{
  stream?.getTracks().forEach(t=>t.stop());stream=null;video.hidden=true;
  document.getElementById('cameraPlaceholder').hidden=false;document.getElementById('cameraStatus').textContent='Camera inactive';
});

document.getElementById('downloadReport')?.addEventListener('click',()=>{
  const report=`STUDENT ENGAGEMENT AI - DEMO REPORT\n\nEngagement Score: 82%\nOn-screen Focus: 78%\nPositive Emotion: 50%\nNeutral Emotion: 14%\nFace Presence: 96%\n\nThis report is generated by the frontend demo. Connect it to the Python detection pipeline for live values.`;
  const blob=new Blob([report],{type:'text/plain'}),a=document.createElement('a');
  a.href=URL.createObjectURL(blob);a.download='engagement_report.txt';a.click();URL.revokeObjectURL(a.href);
});
